INSERT INTO departments (id_department, name, description) VALUES 
(1, 'President', 'General company head'),
(2, 'Development', 'Programmers, coders, testers...'),
(3, 'Marketing', 'Designers and marketing specialists, creatives'),
(4, 'Sales', 'Human resources, recruiters, talent hunters'),
(5, 'Human Resources', 'Human resources, personalists'),
(6, 'Law', 'Company lawyers and notaries'),
(7, 'Economic', 'Accountants and bookkeepers'),
(8, 'Production', 'Modellers, techniques and quality keepers'),
(9, 'Testers', 'Front-end and mobile apps testers'),
(10, 'Core Developers', 'Main company solution developers'),
(11, 'Front-End Developers', 'Front-end developers and coders'),
(12, 'Database Specialists', 'Database administrators and database developers'),
(13, 'Hardware', 'Company hardware support and repairs'),
(14, 'Mobile Apps Development', 'Company mobile solution developers'),
(15, 'Support', 'Company software support'),
(16, 'Analytics', 'Client behaviour and it strategy analytics'),
(17, 'Public Relations', 'Public relations specialists'),
(18, 'UX Designers', 'User experience designers'),
(19, 'Graphic Designers', 'Graphic designers, animators, DTP specialists'),
(20, 'Product Specialists', 'Product designers'),
(21, 'Marketing Specialists', 'Marketing specialists and marketing sales'),
(22, 'Copywriters', 'Copywriters, bloggers'),
(23, 'Creative Specialists', 'Creative people, marketing campaign designers'),
(24, 'Sales Agent Juniors', 'Sales agents - juniors'),
(25, 'Sales Agent Seniors', 'Sales agents - seniors - high skills, big contracts'),
(26, 'Stores', 'Store managers'),
(27, 'Buyers', 'Buyers - components, semi-finished products and materials for products'),
(28, 'Call Center', 'Company call centre workers'),
(29, 'Project Managers', 'Company innovative and new projects managers'),
(30, 'Client Care', 'Client care assistants'),
(31, 'Talent Recruiters', 'Talent recruiters and hunters'),
(32, 'Trainers', 'Employment trainers and '),
(33, 'Psychologists', 'Company psychos fixers'),
(34, 'Team Builders', 'Team building creatives and managers'),
(35, 'Supervisors', 'Managers and departments supervisors'),
(36, 'Health & Safety', 'Employers health and employers wildness correctors'),
(37, 'Employee Relations', 'Employee relations and social specialists'),
(38, 'Common Law', 'Universal lawyers'),
(39, 'Customers Law', 'Customers law specialists'),
(40, 'Contract Law', 'Company contracts specialists'),
(41, 'Employee Law', 'Employee law specialists'),
(42, 'Economy Law', 'Economy law specialists'),
(43, 'Notaries', 'Notaries and their assistants'),
(44, 'Cash Desk', 'Cash desk offices managers and employees'),
(45, 'Analytics', 'Company economy strategy and sales analytics'),
(46, 'Budgets', 'Company budgets directors and assistants'),
(47, 'Taxes & Fees', 'Taxes and fees administrators and attendants'),
(48, 'Investments', 'Company investments administrators'),
(49, 'Payments', 'Payment executors and watchers'),
(50, 'Accountants', 'Company bookkeeper'),
(51, 'Company Property', 'Company properties administrators'),
(52, 'Public Contracts And EU Subsidy', 'Public and EU budgets managers and project administrators'),
(53, 'Quality Checkers', 'Quality checkers and penalty executors'),
(54, 'Constructors', 'New products technical designers and constructors'),
(55, 'Logistics', 'Products transport logistics'),
(56, 'Completers', 'Product completers'),
(57, 'Production Technics', 'Production technics'),
(58, 'Installers', 'Production installers and support'),
(59, 'Modellers', 'Product modellers and new prototype builders');